apiVersion: v1
kind: Service
metadata:
  name: qr-frontend
  namespace: qr-generator
spec:
  type: NodePort 
  selector:
    app: qr-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP