apiVersion: v1
kind: Service
metadata:
  name: qr-frontend
  namespace: qr-generator
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: ClusterIP 
  selector:
    app: qr-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP